# XAMPP Database Constants
host="localhost"
user="root"
password=""
port="3306"
database="sdv-pixelperfect"

# Screenshot Constants
INACTIVE_WHITE_PIXELS_AVERAGE = 2007170
INACTIVE_WHITE_PIXELS_THRESHOLD = 10000 # 6555

INACTIVE_WHITE_PIXELS_TOP_BORDER = INACTIVE_WHITE_PIXELS_AVERAGE + INACTIVE_WHITE_PIXELS_THRESHOLD
INACTIVE_WHITE_PIXELS_BOTTOM_BORDER = INACTIVE_WHITE_PIXELS_AVERAGE - INACTIVE_WHITE_PIXELS_THRESHOLD


ACTIVE_WHITE_PIXELS_AVERAGE = 1673083 
ACTIVE_WHITE_PIXELS_THRESHOLD = 911201

ACTIVE_WHITE_PIXELS_TOP_BORDER = ACTIVE_WHITE_PIXELS_AVERAGE + ACTIVE_WHITE_PIXELS_THRESHOLD
ACTIVE_WHITE_PIXELS_BOTTOM_BORDER = ACTIVE_WHITE_PIXELS_AVERAGE - ACTIVE_WHITE_PIXELS_THRESHOLD


# Screen states
STATE_ACTIVE = 1
STATE_INACTIVE = 0
STATE_SCREENSAVER = -1